#ifndef CPPUNITTESTING_IMAGICNUMBERDEPENDENCIES_H
#define CPPUNITTESTING_IMAGICNUMBERDEPENDENCIES_H

class IMagicNumberDependencies
{
public:
	virtual int MagicNumberHelper(int a, int b) = 0;
};

#endif //CPPUNITTESTING_IMAGICNUMBERDEPENDENCIES_H
